"""reason for cancelling

Revision ID: 29656eba01af
Revises: 7a3d98f52408
Create Date: 2022-12-09 12:15:36.381319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29656eba01af'
down_revision = '7a3d98f52408'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tatus', sa.String(), nullable=True))
        batch_op.drop_column('Status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Status', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('tatus')

    # ### end Alembic commands ###
