"""reason for cancelling

Revision ID: 3cc920cce9ec
Revises: 97a9c7a7edd7
Create Date: 2022-12-06 12:27:41.921710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cc920cce9ec'
down_revision = '97a9c7a7edd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cancellation_reason', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('cancellation_reason')

    # ### end Alembic commands ###
