"""fixed

Revision ID: 4f58d99acdd0
Revises: 613b8299045c
Create Date: 2022-11-30 18:19:56.799769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f58d99acdd0'
down_revision = '613b8299045c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('location_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('review_id', sa.String(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'review', ['review_id'], ['id'])
        batch_op.create_foreign_key(None, 'location', ['location_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('review_id')
        batch_op.drop_column('location_id')
        batch_op.drop_column('user_id')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
